spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products,/api/products/**
          filters:
            - name: Retry
              args:
                retries: 2
                statuses:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                methods:
                  - GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms

        - id: category-service
          uri: lb://product-service
          predicates:
            - Path=/api/categories,/api/categories/**
          filters:
            - name: Retry
              args:
                retries: 2
                statuses:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                methods:
                  - GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory,/api/inventory/**
          filters:
            - name: Retry
              args:
                retries: 2
                statuses:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                methods:
                  - GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders,/api/orders/**
          filters:
            - name: Retry
              args:
                retries: 2
                statuses:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                methods:
                  - GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms